// Code generated by goctl. DO NOT EDIT.
// Source: zrpc.proto

package server

import (
	"context"

	"go-zero-grpc-gateway/common/pb"
	"go-zero-grpc-gateway/zrpc/internal/logic"
	"go-zero-grpc-gateway/zrpc/internal/svc"
)

type ZrpcServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedZrpcServiceServer
}

func NewZrpcServiceServer(svcCtx *svc.ServiceContext) *ZrpcServiceServer {
	return &ZrpcServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ZrpcServiceServer) Ping(ctx context.Context, in *__.Request) (*__.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
