// Code generated by goctl. DO NOT EDIT.
// Source: zrpc.proto

package zrpcservice

import (
	"context"

	"go-zero-grpc-gateway/common/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = __.Request
	Response = __.Response

	ZrpcService interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultZrpcService struct {
		cli zrpc.Client
	}
)

func NewZrpcService(cli zrpc.Client) ZrpcService {
	return &defaultZrpcService{
		cli: cli,
	}
}

func (m *defaultZrpcService) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := __.NewZrpcServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
